namespace EsmCore;

public enum OpCode : byte {
    LoadConst    = 0,
    LoadStr      = 1,
    LoadMem      = 2,
    Store        = 3,
    PopTop       = 4,
    Exit         = 5,
    Jump         = 6,
    JumpIfZero   = 7,
    JumpIfNZero  = 8,
    Do1Not       = 9,
    Do2And       = 10,
    Do2Or        = 11,
    Do2Xor       = 12,
    Do2Left      = 13,
    Do2Right     = 14,
    PrintAscii   = 15,
    PrintBin     = 16,
    PrintDec     = 17,
    PrintHex     = 18,
    InputAscii   = 19,
    InputDec     = 20,
    InputHex     = 21,
    InputBin     = 22,
    InputInt     = 23,
    InputStr     = 24,
}