namespace EsmRuntime.Common;

public enum OpCode : byte {
    AllocStr, // Allocate a string to memory
    AllocSlice, // Allocate a slice of memory
    FreeHeap,
    PushX8, // Push 8 bits to the operand stack
    PushX16, // ...
    PushX32,
    PushX64,
    PushXsize,
    PushGlobalAddr, // Push the address of a value in memory
    Deref, // Try to dereference the address on the stack and then push it
    StoreGlobalX8, // Pop 8 bits from the operand stack and store it to a given address
    StoreGlobalX16, // ...
    StoreGlobalX32,
    StoreGlobalX64,
    StoreGlobalXsize,
    StoreLocX8, // Pop 8 bits from the operand stack and store it to a given local variable
    StoreLocX16, // ...
    StoreLocX32,
    StoreLocX64,
    StoreLocXsize,
    Exit, // Pop 8 bits from the stack and end the program with said exit code
    Jump,
    JumpIfFalse,
    JumpIfTrue,
    NotX8,
    NotX16,
    NotX32,
    NotX64,
    NotXsize,
    AndX8,
    AndX16,
    AndX32,
    AndX64,
    AndXsize,
    OrX8,
    OrX16,
    OrX32,
    OrX64,
    OrXsize,
    XorX8,
    XorX16,
    XorX32,
    XorX64,
    XorXsize,
    LeftX8,
    LeftX16,
    LeftX32,
    LeftX64,
    LeftXsize,
    RightI8,
    RightI16,
    RightI32,
    RightI64,
    RightIsize,
    RightU8,
    RightU16,
    RightU32,
    RightU64,
    RightUsize,
    PlusX8,
    PlusX16,
    PlusX32,
    PlusX64,
    PlusPtr,
    MinusX8,
    MinusX16,
    MinusX32,
    MinusX64,
    MinusXsize,
    EqualX8,
    EqualX16,
    EqualX32,
    EqualX64,
    EqualXsize,
    NEqualX8,
    NEqualX16,
    NEqualX32,
    NEqualX64,
    NEqualXsize,
    MultX8,
    MultX16,
    MultX32,
    MultX64,
    MultXsize,
    DivI8,
    DivI16,
    DivI32,
    DivI64,
    DivIsize,
    DivU8,
    DivU16,
    DivU32,
    DivU64,
    DivUsize,
    ModI8,
    ModI16,
    ModI32,
    ModI64,
    ModIsize,
    ModU8,
    ModU16,
    ModU32,
    ModU64,
    ModUsize,
    // TODO: Casts to usize and isize?
    X8ToU16,
    X16ToU32,
    X32ToU64,
    X8ToI16,
    X16ToI32,
    X32ToI64,
    X64ToX32,
    X32ToX16,
    X16ToX8,
    PrintAscii,
    PrintUtf16,
    PrintU8,
    PrintI8,
    PrintU16,
    PrintI16,
    PrintU32,
    PrintI32,
    PrintU64,
    PrintI64,
    PrintStr,
    InputAscii,
    InputUtf16,
    InputU8,
    InputI8,
    InputU16,
    InputI16,
    InputU32,
    InputI32,
    InputU64,
    InputI64,
    InputUsize,
    InputIsize,
    AllocInputStr,
    PushGlobalFrame,
    PopGlobalFrame,
    PushLocFrame,
    PopLocFrame,
}

public static class OpCodeExt {
    extension(OpCode self) {
        public bool? JumpCondition
            // ReSharper disable once SwitchExpressionHandlesSomeKnownEnumValuesWithExceptionInDefault
            => self switch {
                OpCode.Jump => null,
                OpCode.JumpIfTrue => true,
                OpCode.JumpIfFalse => false,
                _ => throw new InvalidOperationException()
            };

        public static OpCode get_Item(bool? cond)
            => cond switch {
                null => OpCode.Jump,
                false => OpCode.JumpIfTrue,
                true => OpCode.JumpIfFalse,
            };
    }
}