namespace EsmRuntime.Common;

public enum OpCode : byte {
    AllocStr, // Allocate a string to memory
    Push8, // Push 8 bits to the operand stack
    Push16, // ...
    Push32,
    Push64,
    PushPtrSize,
    PushGlobalAddr, // Push the address of a value in memory
    PushLocAddr, // Push the address of an index in the current local frame
    PushGlobalPtr, // pshglbl offs index: pushes the address of
    Deref, // Try to dereference the address on the stack and then push it
    StoreGlobal8, // Pop 8 bits from the operand stack and store it to a given address
    StoreGlobal16, // ...
    StoreGlobal32,
    StoreGlobal64,
    StoreGlobalPtrSize,
    StoreLoc8, // Pop 8 bits from the operand stack and store it to a given local variable
    StoreLoc16, // ...
    StoreLoc32,
    StoreLoc64,
    Exit, // Pop 8 bits from the stack and end the program with said exit code
    Jump,
    JumpIfFalse,
    JumpIfTrue,
    Not8,
    Not16,
    Not32,
    Not64,
    NotPtrSize,
    And8,
    And16,
    And32,
    And64,
    AndPtrSize,
    Or8,
    Or16,
    Or32,
    Or64,
    OrPtrSize,
    Xor8,
    Xor16,
    Xor32,
    Xor64,
    XorPtrSize,
    Left8,
    Left16,
    Left32,
    Left64,
    LeftPtrSize,
    RightI8,
    RightI16,
    RightI32,
    RightI64,
    RightISize,
    RightU8,
    RightU16,
    RightU32,
    RightU64,
    RightUSize,
    Plus8,
    Plus16,
    Plus32,
    Plus64,
    PlusPtrSize,
    Minus8,
    Minus16,
    Minus32,
    Minus64,
    MinusPtrSize,
    Equal8,
    Equal16,
    Equal32,
    Equal64,
    EqualPtrSize,
    NEqual8,
    NEqual16,
    NEqual32,
    NEqual64,
    NEqualPtrSize,
    Mult8,
    Mult16,
    Mult32,
    Mult64,
    MultPtrSize,
    DivI8,
    DivI16,
    DivI32,
    DivI64,
    DivISize,
    DivU8,
    DivU16,
    DivU32,
    DivU64,
    DivUSize,
    ModI8,
    ModI16,
    ModI32,
    ModI64,
    ModISize,
    ModU8,
    ModU16,
    ModU32,
    ModU64,
    ModUSize,
    // TODO: Casts to usize and isize?
    X8ToU16,
    X16ToU32,
    X32ToU64,
    X8ToI16,
    X16ToI32,
    X32ToI64,
    X64ToX32,
    X32ToX16,
    X16ToX8,
    PrintAscii,
    PrintUtf16,
    PrintU8,
    PrintI8,
    PrintU16,
    PrintI16,
    PrintU32,
    PrintI32,
    PrintU64,
    PrintI64,
    PrintStr,
    InputAscii,
    InputUtf16,
    InputU8,
    InputI8,
    InputU16,
    InputI16,
    InputU32,
    InputI32,
    InputU64,
    InputI64,
    InputStr,
    PushGlobalFrame,
    PopGlobalFrame,
}

public static class OpCodeExt {
    extension(OpCode self) {
        public bool? JumpCondition
            // ReSharper disable once SwitchExpressionHandlesSomeKnownEnumValuesWithExceptionInDefault
            => self switch {
                OpCode.Jump => null,
                OpCode.JumpIfTrue => true,
                OpCode.JumpIfFalse => false,
                _ => throw new InvalidOperationException()
            };

        public static OpCode get_Item(bool? cond)
            => cond switch {
                null => OpCode.Jump,
                false => OpCode.JumpIfTrue,
                true => OpCode.JumpIfFalse,
            };
    }
}