namespace EsmRuntime.Common;

public enum OpCode : byte {
    AllocStr,
    Push8,
    Push16,
    Push32,
    Push64,
    PushMem,
    StoreMem8,
    StoreMem16,
    StoreMem32,
    StoreMem64,
    StoreLoc8,
    StoreLoc16,
    StoreLoc32,
    StoreLoc64,
    Exit,
    Jump,
    JumpIfFalse,
    JumpIfTrue,
    Not8,
    Not16,
    Not32,
    Not64,
    And8,
    And16,
    And32,
    And64,
    Or8,
    Or16,
    Or32,
    Or64,
    Xor8,
    Xor16,
    Xor32,
    Xor64,
    Left8,
    Left16,
    Left32,
    Left64,
    RightI8,
    RightI16,
    RightI32,
    RightI64,
    RightU8,
    RightU16,
    RightU32,
    RightU64,
    Plus8,
    Plus16,
    Plus32,
    Plus64,
    Minus8,
    Minus16,
    Minus32,
    Minus64,
    Equal8,
    Equal16,
    Equal32,
    Equal64,
    NEqual8,
    NEqual16,
    NEqual32,
    NEqual64,
    Mult8,
    Mult16,
    Mult32,
    Mult64,
    DivI8,
    DivI16,
    DivI32,
    DivI64,
    DivU8,
    DivU16,
    DivU32,
    DivU64,
    ModI8,
    ModI16,
    ModI32,
    ModI64,
    ModU8,
    ModU16,
    ModU32,
    ModU64,
    X8ToU16,
    X16ToU32,
    X32ToU64,
    X8ToI16,
    X16ToI32,
    X32ToI64,
    X64ToX32,
    X32ToX16,
    X16ToX8,
    PrintAscii,
    PrintUtf16,
    PrintU8,
    PrintI8,
    PrintU16,
    PrintI16,
    PrintU32,
    PrintI32,
    PrintU64,
    PrintI64,
    PrintStr,
    InputAscii,
    InputUtf16,
    InputU8,
    InputI8,
    InputU16,
    InputI16,
    InputU32,
    InputI32,
    InputU64,
    InputI64,
    InputStr,
    PushFrame,
    PopFrame,
}

public static class OpCodeExt {
    extension(OpCode self) {
        public bool? JumpCondition
            // ReSharper disable once SwitchExpressionHandlesSomeKnownEnumValuesWithExceptionInDefault
            => self switch {
                OpCode.Jump => null,
                OpCode.JumpIfTrue => true,
                OpCode.JumpIfFalse => false,
                _ => throw new InvalidOperationException()
            };

        public static OpCode get_Item(bool? cond)
            => cond switch {
                null => OpCode.Jump,
                false => OpCode.JumpIfTrue,
                true => OpCode.JumpIfFalse,
            };
    }
}